apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  # Replace below value with base64 of your SECRET_KEY
  # Example: echo -n 'super-secret' | base64
  SECRET_KEY: cmFuZG9tLXNlY3JldA==
